'use client';

//Updated with clerk

import { ClerkProvider } from '@clerk/nextjs';
import { SWRConfig } from 'swr';
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider frontendApi={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
          <SWRConfig value={{ /* your SWR config */ }}>
            {children}
          </SWRConfig>
        </ClerkProvider>
      </body>
    </html>
  );
}

//PREVIOUS CODE
/*import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}*/
